import streamlit as st
from utils.styles import load_css
from utils.constants import (
    MODEL_NAME,
    N_CLASSES,
    N_FEATURES,
    N_PARTICIPANTS,
)


def show():

    load_css()

    # HERO
    st.title("About")

    st.write(
        """
    This dashboard presents the final outcomes of the project
    **AI-Assisted Screening of Parkinson's Disease**, developed as part of the
    Master of Data Analytics program at the University of Niagara Falls Canada.

    The proposed framework combines wearable sensor measurements,
    non-motor symptom questionnaire responses, and demographic information
    to support the early screening of Parkinson's disease using an
    interpretable multimodal machine learning approach.
    """
    )

    st.divider()

    # RESEARCH OBJECTIVES
    st.header("Research Objectives")
    st.subheader("General Objective")
    st.info(
    """
    Develop and evaluate an explainable multimodal machine learning framework
    that integrates smartwatch movement signals, non-motor symptom questionnaire
    responses, and demographic information to differentiate among Healthy Controls
    (HC), Parkinson's Disease (PD), and Other Movement Disorders (OMD).

    The framework compares modality-specific and multimodal approaches,
    evaluates participant-level predictive performance, and applies SHAP
    explainability to identify the factors influencing model predictions.
    """
    )

    st.subheader("Specific Objectives")
    st.markdown(
    """
    - Audit, clean, and preprocess demographic, questionnaire, and wearable sensor data.

    - Extract clinically interpretable movement features from accelerometer and gyroscope recordings.

    - Develop modality-specific machine learning models using each data source independently.

    - Develop multimodal models integrating wearable, questionnaire, and demographic information.

    - Implement participant-level validation strategies to prevent data leakage.

    - Compare candidate models using multiclass evaluation metrics.

    - Apply SHAP explainability to identify the variables contributing most strongly to model predictions.

    - Develop an academic screening-support prototype capable of communicating predictions, uncertainty, performance, and explanations.
    """
    )
    st.divider()

    # DATASET
    st.header("Dataset")

    c1, c2, c3, c4 = st.columns(4)

    c1.metric("Participants", N_PARTICIPANTS)
    c2.metric("Selected Features", N_FEATURES)
    c3.metric("Classes", N_CLASSES)
    c4.metric("Final Model", MODEL_NAME)

    st.write(
    """
    The multimodal dataset combines three complementary sources of information:

    - **Wearable Sensors**
    - Bilateral smartwatch recordings
    - Accelerometer
    - Gyroscope

    - **Questionnaire**
    - Non-Motor Symptoms Questionnaire (NMSQuest)

    - **Demographics**
    - Age
    - Sex
    - Clinical information
    """
    )

    st.divider()

    # METHODOLOGY
    st.header("Methodology")

    st.markdown(
    """
    ```text
    Data Collection
            │
    Data Cleaning
            │
    Feature Engineering
            │
    Feature Selection
            │
    Participant-Level Validation
            │
    Machine Learning
            │
    Performance Evaluation
            │
    SHAP Explainability
            │
    Interactive Dashboard
    """
    )

    st.divider()

    # TECHNOLOGIES
    st.header("Technologies")
    c1,c2,c3 = st.columns(3)
    with c1:
        st.success("🐍 Python")
        st.success("📊 Pandas")
        st.success("🔬 NumPy")
    with c2:
        st.success("🌲 XGBoost")
        st.success("🤖 Scikit-learn")
        st.success("📈 SHAP")
    with c3:
        st.success("🎈 Streamlit")
        st.success("📉 Matplotlib")
        st.success("💾 Joblib")
    st.divider()

    # DEVELOPMENT TEAM
    st.header("Development Team")

    st.markdown(
    """
    **Master of Data Analytics**
    University of Niagara Falls Canada
    Summer 2026
    """
    )
    st.markdown(
    """
    - Allison Janet Bazan Luna
    - Daniela Leon Granados
    - Kadian Hutchinson
    - Ophelia Sasha-Gay Bramwell
    - Priti Khadka
    """
    )

    st.divider()

    # DISCLAIMER
    st.header("Disclaimer")
    st.warning(
    """
    This application was developed exclusively for academic research purposes.

    The proposed framework is intended to support research on Parkinson's disease
    screening and should not be interpreted as a clinical diagnostic tool.
    Predictions generated by this system are not intended to replace professional
    medical evaluation or clinical decision-making.
    """
    )